openapi: 3.0.4
info:
  title: Superhero Name Generator
  description: Generate unique superhero names using dynamic templates and word combinations.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/superheroname:
    get:
      summary: Generate Superhero Name
      description: Generate unique superhero names using dynamic templates and word combinations.
      operationId: superheroname
      parameters:
      - name: style
        in: query
        schema:
          type: string
        required: false
        description: 'Name style: dark, cosmic, elemental, tech, heroic, mystic'
        example: dark
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  name: Shadow Bringer
                  style: dark
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
